### PR TITLE
[WIP] feat: Lint for reg<whatever> types outside of pg_catalog

### PR DESCRIPTION
**Pull request by bymayanksingh**
## What kind of change does this PR introduce?

Adds a lint to check if there are any tables that have data types that are not supported by pg_upgrade command, this PR aims to fix : issue #55 

## What is the current behavior?

Current pg_upgrade would fail for those tables where the following data types as present for certain columns: 

1. regcollation
2. regconfig
3. regdictionary
4. regnamespace
5. regoper
6. regoperator
7. regproc
8. regprocedure

## What is the new behavior?

this lint will highlight any table that contains the above data types when pg_upgrade command is run.

## Additional context

To test the lint query locally following steps can be used: 

run the following command to open psql, which is a terminal based frontend to postgres.
`>psql`

then inside psql, run

```
CREATE DATABASE test_db;

CREATE SCHEMA test_schema;

CREATE TABLE test_schema.test_table1 (
    id SERIAL PRIMARY KEY,
    col1 regcollation,
    col2 regclass
);

CREATE TABLE pg_catalog.test_table2 (
    id SERIAL PRIMARY KEY,
    col1 regconfig,
    col2 regtype
);

CREATE SCHEMA lint;
```

Create the view:

```
CREATE VIEW lint."unsupported_reg_types" AS
SELECT
  'unsupported_reg_types' AS name,
  'Unsupported reg* Types' AS title,
  'WARN' AS level,
  'EXTERNAL' AS facing,
  ARRAY['MIGRATION'] AS categories,
  'Identifies columns using unsupported reg* types outside pg_catalog schema, which prevents database upgrades using pg_upgrade.' AS description,
  FORMAT(
    'Table `%s.%s` has a column `%s` with unsupported reg* type `%s`.',
    n.nspname, c.relname, a.attname, t.typname
  ) AS detail,
  'https://supabase.com/docs/guides/database/database-linter?lint=unsupported_reg_types' AS remediation,
  jsonb_build_object(
    'schema', n.nspname,
    'table', c.relname,
    'column', a.attname,
    'type', t.typname
  ) AS metadata,
  FORMAT('unsupported_reg_types_%s_%s_%s', n.nspname, c.relname, a.attname) AS cache_key
FROM
  pg_catalog.pg_attribute a
  JOIN pg_catalog.pg_class c ON a.attrelid = c.oid
  JOIN pg_catalog.pg_namespace n ON c.relnamespace = n.oid
  JOIN pg_catalog.pg_type t ON a.atttypid = t.oid
WHERE
  t.typname IN ('regcollation', 'regconfig', 'regdictionary', 'regnamespace', 'regoper', 'regoperator', 'regproc', 'regprocedure')
  AND n.nspname NOT IN ('pg_catalog', 'information_schema');
```

Finally, run the following query:

`SELECT * FROM lint."unsupported_reg_types";
`

Output:

| name               | title                     | level | facing   | categories | description                                                                                                                     | detail                                                                                          | remediation                                                                                     | metadata                                                                                       | cache_key                                                       |
|--------------------|---------------------------|-------|----------|------------|---------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------|-----------------------------------------------------------------|
| unsupported_reg_types | Unsupported reg* Types | WARN  | EXTERNAL | {MIGRATION} | Identifies columns using unsupported reg* types outside pg_catalog schema, which prevents database upgrades using pg_upgrade. | Table `test_schema.test_table1` has a column `col1` with unsupported reg* type `regcollation`. | [Documentation](https://supabase.com/docs/guides/database/database-linter?lint=unsupported_reg_types) | {"type": "regcollation", "table": "test_table1", "column": "col1", "schema": "test_schema"} | unsupported_reg_types_test_schema_test_table1_col1              |
| unsupported_reg_types | Unsupported reg* Types | WARN  | EXTERNAL | {MIGRATION} | Identifies columns using unsupported reg* types outside pg_catalog schema, which prevents database upgrades using pg_upgrade. | Table `test_schema.test_table2` has a column `col1` with unsupported reg* type `regconfig`.   | [Documentation](https://supabase.com/docs/guides/database/database-linter?lint=unsupported_reg_types) | {"type": "regconfig", "table": "test_table2", "column": "col1", "schema": "test_schema"}   | unsupported_reg_types_test_schema_test_table2_col1              |

### CODE REVIEW

**Comment by olirice** [comment]
sorry @bymayanksingh I didn't notice the `[WIP]` in the title here and thought you were passing it to me for review

In the future please either hold off on opening a PR or put it in `draft` state if it isn't ready

If you'd like to see the changes I made they're available in this [commit](https://github.com/supabase/splinter/pull/92/commits/36864e9687d2280a098c7c64551c69c80908d445)

Thanks for your help!

**Review by olirice — APPROVED** [review]

**Comment by bymayanksingh** [comment]
Hey @olirice 

Thank you for the feedback and the changes you made in the commit. I apologize for the confusion; I’ll make sure to use the draft state for PRs that are still in progress in the future.

I’m eager to learn and contribute more to the project. Can you label other issues as good first issues, if any?

I'll also join Supabase discord community, assuming you'll be there & we can streamline the conversations.

**Comment by olirice** [comment]
> Can you label other issues as good first issues, if any?
definitely!
how does https://github.com/supabase/splinter/issues/25 look?

**Comment by bymayanksingh** [comment]
> > Can you label other issues as good first issues, if any?
> 
> definitely! how does #25 look?

looks good, let me explore that, can you assign it to me?

**Pull request merged**
